INFERANALYZE= /usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/../../../bin/InferAnalyze $(INFER_OPTIONS) -results_dir '/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out'

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 cl15 cl16 cl17 cl18 cl19 cl20 cl21 cl22 cl23 cl24 cl25 cl26 cl27 cl28 cl29 cl30 cl31 cl32 cl33 cl34 cl35 cl36 cl37 cl38 cl39 cl40 cl41 cl42 

default: test

all: test

test: $(CLUSTERS)
	echo ""
#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/BroadcastReceiverTest.java.d134b40a0835341613d340029125f213
cl1: 
	$(INFERANALYZE) -cluster xcl1.cluster >cl1

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/BuildConfig.java.7114fcf8913caf42b2daec5eb6ae446c
cl2: 
	$(INFERANALYZE) -cluster xcl2.cluster >cl2

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/BuildConfig.java.7de7f848884f088f955e9545413f024a
cl3: 
	$(INFERANALYZE) -cluster xcl3.cluster >cl3

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/CheckIntentParseUriRuleTest.java.a21fab199c6b9213e4df3f13ff9936be
cl4: 
	$(INFERANALYZE) -cluster xcl4.cluster >cl4

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/CheckOverrideOpenFileTest.java.7253e56ae59faead7ffa460254d91c77
cl5: 
	$(INFERANALYZE) -cluster xcl5.cluster >cl5

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/CheckSqlRawqueryRuleTest.java.01462a3d3868d767ea969ee8f61278e9
cl6: 
	$(INFERANALYZE) -cluster xcl6.cluster >cl6

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/DDosBlockRuleTest.java.22e0841eae30b83b10e949993e111260
cl7: 
	$(INFERANALYZE) -cluster xcl7.cluster >cl7

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/DisplayLeakActivity2.java.03bf4bf1e51fad18e1733e4ee1a07f1f
cl8: 
	$(INFERANALYZE) -cluster xcl8.cluster >cl8

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/DisplayLeakActivity3.java.49a38e2aa9f93b922103320f2d66c399
cl9: 
	$(INFERANALYZE) -cluster xcl9.cluster >cl9

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/DisplayLeakActivity4.java.05100fe04a58fc7a3db7d87d2a15039f
cl10: 
	$(INFERANALYZE) -cluster xcl10.cluster >cl10

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/DisplayLeakActivity5.java.c49afa00095f55832dcf4bfc3c269dc6
cl11: 
	$(INFERANALYZE) -cluster xcl11.cluster >cl11

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/DisplayLeakActivity6.java.df1e32d005e607bf977992e02cdca19f
cl12: 
	$(INFERANALYZE) -cluster xcl12.cluster >cl12

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/DisplayLeakActivity7.java.a0dd6c91f6058f08fd4586d45cec2f98
cl13: 
	$(INFERANALYZE) -cluster xcl13.cluster >cl13

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/DisplayLeakActivity8.java.9ddaab205202e6158d0cbe30b28d4498
cl14: 
	$(INFERANALYZE) -cluster xcl14.cluster >cl14

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/DisplayLeakActivity9.java.95a035b6baafb172151d7c3f9b9e1f38
cl15: 
	$(INFERANALYZE) -cluster xcl15.cluster >cl15

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/ExampleUnitTest.java.348a2b1bd715053e2eb1921b0bae7ab2
cl16: 
	$(INFERANALYZE) -cluster xcl16.cluster >cl16

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/FragmentRuleTest.java.951e65ce26b1512fa2f3ae4c3afbc94f
cl17: 
	$(INFERANALYZE) -cluster xcl17.cluster >cl17

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/LogTypeRuleTest.java.e99c1a68e54527a0a2b629b59858944e
cl18: 
	$(INFERANALYZE) -cluster xcl18.cluster >cl18

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/NullPointerTest.java.64cd904e0be1f72de82c23a7093bc168
cl19: 
	$(INFERANALYZE) -cluster xcl19.cluster >cl19

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.02f5e2e585c74b3ef0695eeab45f2ef9
cl20: 
	$(INFERANALYZE) -cluster xcl20.cluster >cl20

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.030c1e532b482606e77cd89aad2b1284
cl21: 
	$(INFERANALYZE) -cluster xcl21.cluster >cl21

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.0491aee41b2e89ef45d0a9bcaae5b11f
cl22: 
	$(INFERANALYZE) -cluster xcl22.cluster >cl22

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.09fad7cad32f7642fc08bbedb65436e2
cl23: 
	$(INFERANALYZE) -cluster xcl23.cluster >cl23

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.21f2d72126b640418e8c48ff9f86ed7d
cl24: 
	$(INFERANALYZE) -cluster xcl24.cluster >cl24

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.3dbd9e316cc42f5f4b4dc644f72f71e1
cl25: 
	$(INFERANALYZE) -cluster xcl25.cluster >cl25

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.4a8b79952e3ca5106c0500f148402b3e
cl26: 
	$(INFERANALYZE) -cluster xcl26.cluster >cl26

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.4dac68a4a12f16c5b1dd6227bbe85323
cl27: 
	$(INFERANALYZE) -cluster xcl27.cluster >cl27

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.578e0a78e439ce0ec491f61e13b5af2b
cl28: 
	$(INFERANALYZE) -cluster xcl28.cluster >cl28

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.5a735abd631d050591f33cd3a7d9a4c2
cl29: 
	$(INFERANALYZE) -cluster xcl29.cluster >cl29

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.968388eff77adeb85d4b80522b71edca
cl30: 
	$(INFERANALYZE) -cluster xcl30.cluster >cl30

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.99ffd166a8154b5ba690dc0366a08c9b
cl31: 
	$(INFERANALYZE) -cluster xcl31.cluster >cl31

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.a3a7414bcb671140be079a93f84256a3
cl32: 
	$(INFERANALYZE) -cluster xcl32.cluster >cl32

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.a9974d014cbe163cd86ab3dc17465606
cl33: 
	$(INFERANALYZE) -cluster xcl33.cluster >cl33

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.b52479ac4e5053e814143666631cf52d
cl34: 
	$(INFERANALYZE) -cluster xcl34.cluster >cl34

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.bb16a13413e8e00a0eca7f8eee235063
cl35: 
	$(INFERANALYZE) -cluster xcl35.cluster >cl35

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.ca892a4ee249768ea1ffdda1610c4582
cl36: 
	$(INFERANALYZE) -cluster xcl36.cluster >cl36

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.f92ad9af0c5d2ce9257639f6479c6ab9
cl37: 
	$(INFERANALYZE) -cluster xcl37.cluster >cl37

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.fbbb47ac27ba1858f65baba6044b1e6b
cl38: 
	$(INFERANALYZE) -cluster xcl38.cluster >cl38

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/R.java.fe74767c8d8df9911c249d4e1ba17b3d
cl39: 
	$(INFERANALYZE) -cluster xcl39.cluster >cl39

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/SharedPerferenceDataRuleTest.java.f8d45487be0b37b40865bc96459fa4c7
cl40: 
	$(INFERANALYZE) -cluster xcl40.cluster >cl40

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/SimpleTest.java.3b2b680bc50db2e1798ded4f5be1cc7d
cl41: 
	$(INFERANALYZE) -cluster xcl41.cluster >cl41

#/Users/liujun-iri/Desktop/RuleTestProjects/androidRuleTestCases/infer-out/captured/WebViewRuleTest.java.807baf16029debd194b82ad299da9112
cl42: 
	$(INFERANALYZE) -cluster xcl42.cluster >cl42


clean:
	rm -f $(CLUSTERS)
